// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRmcc1yRVcczvx8GoU61EsFn9WIoGERxg',
    appId: '1:1099252653009:web:a466d7a9972e2dd05e5ef0',
    messagingSenderId: '1099252653009',
    projectId: 'doument-management-app',
    authDomain: 'doument-management-app.firebaseapp.com',
    storageBucket: 'doument-management-app.firebasestorage.app',
    measurementId: 'G-M89TTH1DX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4MUwAOAzouoRQOxYDA75AftEKrNW7Lw',
    appId: '1:1099252653009:android:e23668d1fb7f29f85e5ef0',
    messagingSenderId: '1099252653009',
    projectId: 'doument-management-app',
    storageBucket: 'doument-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zLZovV6l92dN6VbT7cORU4rnHD8wlBw',
    appId: '1:1099252653009:ios:9436372b78d8b9515e5ef0',
    messagingSenderId: '1099252653009',
    projectId: 'doument-management-app',
    storageBucket: 'doument-management-app.firebasestorage.app',
    iosBundleId: 'com.example.realTimeMaps',
  );

}